
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="sleeplib"
version="${file.jarVersion}"
displayName="SleepLib"
logoFile="examplemod.png"
credits="Sleepwalker"
authors="Sleepwalker"
description='''
==================================
======= Игры убивают детей =======
==================================
'''

[[dependencies.sleeplib]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sleeplib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
